### ISSUE TITLE
Album Art?

### ISSUE THREAD

**Issue by TRPB** [ToppleKek/discord-rhythmbox-plugin#11]
When using Spotify, it sets the large image to the album art.  Is that possible here?

The art should be readable via dbus from rhythmbox failing that could be extracted by another module from the file. However, I can't see where it's currently getting the image from it sets `large_image="rhythmbox"` but I can't see how discord identifies the icon that "rhythmbox" is referring to.

**Comment by ToppleKek** [comment]
Discord has special integration with Spotify which is why it can show album art. All image assets for normal "games" need to be uploaded in the discord developer panel (where you would give a key, in this case the key for the Rhythmbox logo is `rhythmbox`).

It is possible to upload images via the API and provide a unique key, but this would require the end user to make an application on the Discord developer portal and provide the client ID themselves along with their token for authentication. I have done this for other projects but I do not currently plan to implement it in this simple plugin. If anyone who is better at python than me is wanting to, please do!

**Comment by B34rly** [comment]
I began working an implementation of this for myself and will probably upload the additions but can you clarify what you mean by
> It is possible to upload images via the API and provide a unique key
Do you mean automatically or manually here? I couldn't find any reference to an automatically uploading an image through pypresence.
If it is done manually, then the most that can be added is an output folder with the covers with the fitting naming scheme that must be uploaded to the user's own application on Discord's portal.

**Comment by ToppleKek** [comment]
pypresence does not provide a way to upload assets. Discord doesn't really want you to do it like this but you can by making a POST request to the API endpoint `https://discordapp.com/api/oauth2/applications/APPLICATION_ID/assets` with the payload:
```json
{
  "name": "unique_key",
  "image": "data:image/png;base64,base64 image data"
}
```
Keep in mind that when you do this, you have a maximum of 150 assets per application on discord at a given time and you will have to keep track of how many you have uploaded and probably the timestamp that you uploaded them at. When you reach 150 assets you could for example delete the oldest asset, or delete the least used asset, etc. 

It's not too hard to implement, but I don't think that this API is documented and I don't know if we are supposed to be using it. So if we're not, shhh!

**Comment by TRPB** [comment]
You can also set it to "Listening to" as of a recent update. The API is here: https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum 

I'm not sure it will help with album art but it may open up more possibilities.

**Comment by B34rly** [comment]
I've uploaded my changes to a [fork](https://github.com/B34rly/discord-rhythmbox-plugin/blob/master/discord-status.py) and finding the album art works mostly fine, excluding that it gets the image by looking through the folder of the playing song, so if there isn't a cover.png nothing is found. It can be worked over by getting the cover from the embed data of the song but it's annoying to implement with all the different file extensions. Rhythmbox also saves all it's cover art to `~/.cache/rhythmbox/album-art` but I'm unsure of how they're named (3 character something, some alphanumeric others purely numeric) so I can't use it. The images also aren't always .png's so that's something else that I didn't account for.

However, the images aren't showing up in the discord developer portal meaning *something* is wrong with the request. It's most likely to be something out of

- How I've got the base64 data in some way
- The payload, particularly with data:image/png. As not all the images are pngs I decided to change it to just data:image/ but it's probably malformed in some way there
- The image doesn't meet the 512*512 minimum for assets

I did manually upload an image and it worked, so the problem is somewhere in the request.

**Comment by B34rly** [comment]
After uploading the bases to a test html (`<img src="data:image/;base64, ...>`) site I found that the encoding is not the problem as most of the data read fine, and the `data:image/` wasn't a problem either so the cause is most likely the  API request. Did you get it wrong somehow  or am I doing something wrong?

**Comment by ToppleKek** [comment]
Are you authenticating? Is that payload being encoded as JSON? Did you even look at the response from your POST?

**Comment by B34rly** [comment]
I've now (hopefully) properly set up the headers, but I haven't implemented a way to get the auth token. How did you get yours in this application? Did you set up a server to use as the URI for discord?

**Comment by ToppleKek** [comment]
I just had the user provide it in the settings.

**Comment by B34rly** [comment]
I got it working, although for songs without a cover.png it won't work unless a different method to get the album art is used. 
Can I get the icons (rhythmbox, play, pause) that you used in your application so I can upload them to Discord's assets?

**Comment by ToppleKek** [comment]
Sorry, got busy this week.
Unknown: https://cdn.discordapp.com/app-assets/589905203533185064/589905260307546149.png?size=2048
Stop: https://cdn.discordapp.com/app-assets/589905203533185064/589905259972001792.png?size=2048
Pause: https://cdn.discordapp.com/app-assets/589905203533185064/589905259967545378.png?size=2048
Play: https://cdn.discordapp.com/app-assets/589905203533185064/589905260001099778.png?size=2048
Rhythmbox: https://cdn.discordapp.com/app-assets/589905203533185064/589905260328255493.png?size=2048

**Comment by B34rly** [comment]
I figured out how to get the images from the database, had to copy a lot of code from the webremote plugin first. I'll clean up and upload this new code soon. 
Should I write some code to upload all these assets you sent as a first time set up or just instruct the user to do it manually? They also need to use their own discord application, so uploading the assets shouldn't be too much extra effort lol

**Comment by ToppleKek** [comment]
I would have implemented it in a way that the album art is automatically uploaded whenever it is needed. Such as when they play a new album. 

I also am planning on rewriting this plugin, and I'll include this feature as well. If you want, you can put what you have into a pull request I'll merge it to another branch where I'll be doing some work on the whole plugin. Just so we don't have anything broken in master. Thanks so much!

**Comment by B34rly** [comment]
Oh sorry, the album art is automatically uploaded but these other icons are manual. I'll add my code into another branch soon!

**Comment by B34rly** [comment]
I've uploaded the code to [my own fork](https://github.com/B34rly/discord-rhythmbox-plugin) since i don't have branch access lol, you can test it and add it to the main branch of this
